using CityBuilderCore;
using System;

namespace CityBuilderTown
{
    /// <summary>
    /// holds the "personality" of a <see cref="TownWalker"/>, randomly generated when a walker spawns
    /// </summary>
    [Serializable]
    public struct TownIdentity
    {
        public string FirstName;
        public string LastName;
        public float Heigth;
        public float Width;
        public float Lifespan;
        public float EnergyCapacity;
        public float EnergyRecovery;
        public float FoodCapacity;
        public float FoodLoss;
        public float WarmthCapacity;
        public float WarmthLoss;

        public string FullName => FirstName + " " + LastName;

        public static TownIdentity Generate() => new TownIdentity()
        {
            FirstName = FirstNames.Random(),
            LastName = LastNames.Random(),
            Heigth = UnityEngine.Random.Range(MinHeight, MaxHeight),
            Width = UnityEngine.Random.Range(MinWidth, MaxWidth),
            Lifespan = UnityEngine.Random.Range(MinLifespan, MaxLifespan),
            EnergyCapacity = UnityEngine.Random.Range(MinEnergyCapacity, MaxEnergyCapacity),
            EnergyRecovery = UnityEngine.Random.Range(MinEnergyRecovery, MaxEnergyRecovery),
            FoodCapacity = UnityEngine.Random.Range(MinFoodCapacity, MaxFoodCapacity),
            FoodLoss = UnityEngine.Random.Range(MinFoodLoss, MaxFoodLoss),
            WarmthCapacity = UnityEngine.Random.Range(MinWarmthCapacity, MaxWarmthCapacity),
            WarmthLoss = UnityEngine.Random.Range(MinWarmthLoss, MaxWarmthLoss)
        };

        private const float MinHeight = 0.9f;
        private const float MaxHeight = 1.1f;
        private const float MinWidth = 0.9f;
        private const float MaxWidth = 1.1f;

        private const float MinLifespan = 30 * 60;
        private const float MaxLifespan = 35 * 60;

        private const float MinEnergyCapacity = 15f;
        private const float MaxEnergyCapacity = 20f;
        private const float MinEnergyRecovery = 2f;
        private const float MaxEnergyRecovery = 3f;

        private const float MinFoodCapacity = 200f;
        private const float MaxFoodCapacity = 250f;
        private const float MinFoodLoss = 1f;
        private const float MaxFoodLoss = 1.1f;

        private const float MinWarmthCapacity = 250f;
        private const float MaxWarmthCapacity = 300f;
        private const float MinWarmthLoss = 0.9f;
        private const float MaxWarmthLoss = 1.1f;

        private static readonly string[] FirstNames =
        {
"Ebafor",
"Peres",
"Horwor",
"Trunvyn",
"Amaradwel",
"Jiyaol",
"Sedham",
"Ramaany",
"Jahucan",
"Bevry",
"Jearocol",
"Judon",
"Wityl",
"Wogailil",
"Maecabyn",
"Ailrorewhinim",
"Bukaichon",
"Bity",
"Adedon",
"Hocien",
"Fecin",
"Tedrirales",
"Athodham",
"Leihan",
"Perrosol",
"Cowinlam",
"Rodinu",
"Nores",
"Ivitim",
"Nozol",
"Peluminon",
"Reces",
"Monim",
"Rohar",
"Elochy",
"Jorulareth",
"Hecer",
"Arneyail",
"Adimim",
"Gofar",
"Terwor",
"Wivryn",
"Hammahil",
"Vaadid",
"Heron",
"Ranahan",
"Elbaazien",
"Rulwintalan",
"Foyimu",
"Mupal",
"Wocer",
"Kisy",
"Sotim",
"Wuder",
"Soly",
"Ladwutim",
"Maagy",
"Mahadran",
"Andobyn",
"Oratyn",
"Caarifyn",
"Sinyson",
"Otichid",
"Nachir",
"Witewelal",
"Norupar",
"Vigim",
"Isakin",
"Darewelar",
"Joayay",
"Blestiajimu",
"Vurim",
"Jurohes",
"Roawelien",
"Agnyarwynim",
"Cazram",
"Meges",
"Taraluanin",
"Davuiaregel",
"Peyer",
"Raenadal",
"Sagor",
"Hoton",
"Dernouwhinor",
"Kismoranol",
"Mashoriocyl",
"Agnatan",
"Pevid",
"Oraenam",
"Adaofalan",
"Cimeinar",
"Jorobril",
"Riter",
"Gadhor",
"Alidres",
"Geofrody",
"Dernudricimu",
"Mosherdigural",
"Jamar",
"Ebozrim",
"Cabranelleve",
"Vandiminen",
"Myrelliannatin",
"Lemenia",
"Hody",
"Rafelandary",
"Harillinen",
"Beldelia",
"Coshiha",
"Cianarne",
"Zetin",
"Phaedrariry",
"Hila",
"Maeten",
"Tianeninia",
"Rashollen",
"Totle",
"Rominele",
"Komamy",
"Cviata",
"Maglerinen",
"Mabrasa",
"Liandravin",
"Chesmeven",
"Ruvei",
"Cabrenwinailinen",
"Femaitei",
"Temiananin",
"Jeonila",
"Ispalera",
"Malinahen",
"Nesishanina",
"Dide",
"Cadsiehia",
"Falahia",
"Zemerinen",
"Cabrisy",
"Jiera",
"Mane",
"Elsarivinen",
"Fumia",
"Adodinen",
"Thete",
"Zirinen",
"Tabimese",
"Memarionin",
"Hirinen",
"Belyllallinen",
"Bonwheanei",
"Jeruta",
"Kwesandrin",
"Cavidinen",
"Sherarinen",
"Deaneavin",
"Isperene",
"Coiranerly",
"Kavin",
"Pelenen",
"Teseven",
"Riannerene",
"Covunamia",
"Katierida",
"Aderevinen",
"Janondre",
"Gainailei",
"Sonailin",
"Ellarlaldry",
"Bonwhisin",
"Liririn",
"Alerisinen",
"Fota",
"Galiranen",
"Malolarrin",
"Faraona",
"Fyrelleny",
"Cetyrellenia",
"Janindirininen",
"Analen",
"Deditlen",
"Kole",
"Salania",
"Janida",
"Cadsulin",
"Jyllaninen",
"Cavedrana",
"Sarlasa",
"Emretla",
"Danerinen",
"Lviame",
"Movrannasei",
"Seonandrathy",
"Liandrianala",
"Kellemia",
"Emremin",
"Tarnady",
"Woma",
"Aelidei",
"Thaiserinen",
"Cianasin",
"Edakimade",
        };
        private static readonly string[] LastNames =
        {
"Noryrag",
"Paenyran",
"Gororon",
"Honon",
"Telaem",
"Pranodred",
"Athyne",
"Noraera",
"a'Lagin",
"Kenyr",
"Keniaya",
"Daged",
"Moerys",
"Tevron",
"Torolin",
"Lothiar",
"Steperan",
"Banilin",
"Pyne",
"Gororon",
"Stepaera",
"Harathor",
"Pemelle",
"Dolrin",
"Naerain",
"Athyr",
"Peran",
"Damain",
"Krynind",
"Naeroron",
"Saloihan",
"a'Dag",
"Bachira",
"Mathaidhrin",
"Lanodred",
"Paeniros",
"Stepevron",
"Merraem",
"Solineos",
"al'Doron",
"Pranera",
"Saneran",
"Pranyros",
"Mathaim",
"Machagin",
"Haenathor",
"Machiaw",
"Telenne",
"Paenynar",
"Athys",
"Dyl",
"Toraw",
"Sanyan",
"Cauthys",
"Telonche",
"Solinas",
"Ayaem",
"Bashan",
"Ayevron",
"Charathor",
"Melyran",
"Falaidhrin",
"a'Dan",
"a'Lyron",
"Moeryros",
"Manara",
"Moereran",
"Krynara",
"Fathor",
"al'Miaya",
"Falon",
"Atheron",
"a'Dear",
"Bryninas",
"Paenynar",
"Harineos",
"Salineos",
"Athyrag",
"Veleran",
"Stepaw",
"Lothed",
"Hagineos",
"Nored",
"Gorar",
"Hagyr",
"a'Niaya",
"Togan",
"Merraim",
"Falaidhrin",
"Kiryron",
"al'Dinas",
"Lamevron",
"Haenyros",
"Cauthanche",
"Charaim",
"Honeron",
"Mantara",
"Aldalin",
"Mathaidhrin",
"Mantyran",
        };
    }
}
